spring.application.name=little-babel

spring.jpa.properties.hibernate.validator.apply_to_ddl=false

open-library.base-url=https://openlibrary.org
open-library.user-agent=little-babel-dev/0.1 (${OPEN_LIBRARY_CONTACT:contact-not-set})